# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload.proto',
  package='measurements',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rpayload.proto\x12\x0cmeasurements\"\xbf\x01\n\x12SingleLocationData\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0e\n\x06zoneId\x18\x03 \x01(\x05\x12\x12\n\nhemisphere\x18\x04 \x01(\x08\x12\x10\n\x08northing\x18\x05 \x01(\x05\x12\x0f\n\x07\x65\x61sting\x18\x06 \x01(\x05\x12\x0f\n\x07\x62\x65\x61ring\x18\x07 \x01(\x05\x12\r\n\x05speed\x18\x08 \x01(\x05\x12\x10\n\x08\x61\x63\x63uracy\x18\t \x01(\x02\x12\x0b\n\x03ttl\x18\n \x01(\x05\"T\n\nDensityMap\x12\x16\n\x0esenderDeviceId\x18\x01 \x01(\x05\x12.\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32 .measurements.SingleLocationData\"W\n\x0bWarnMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nvalidUntil\x18\x02 \x01(\x03\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\"\xaa\x01\n\x16LocationMessageWrapper\x12\x32\n\x06single\x18\x01 \x01(\x0b\x32 .measurements.SingleLocationDataH\x00\x12\'\n\x03map\x18\x02 \x01(\x0b\x32\x18.measurements.DensityMapH\x00\x12,\n\x07message\x18\x03 \x01(\x0b\x32\x19.measurements.WarnMessageH\x00\x42\x05\n\x03msgb\x06proto3'
)




_SINGLELOCATIONDATA = _descriptor.Descriptor(
  name='SingleLocationData',
  full_name='measurements.SingleLocationData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='measurements.SingleLocationData.deviceId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='measurements.SingleLocationData.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zoneId', full_name='measurements.SingleLocationData.zoneId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hemisphere', full_name='measurements.SingleLocationData.hemisphere', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='northing', full_name='measurements.SingleLocationData.northing', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='easting', full_name='measurements.SingleLocationData.easting', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bearing', full_name='measurements.SingleLocationData.bearing', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='measurements.SingleLocationData.speed', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='measurements.SingleLocationData.accuracy', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ttl', full_name='measurements.SingleLocationData.ttl', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=223,
)


_DENSITYMAP = _descriptor.Descriptor(
  name='DensityMap',
  full_name='measurements.DensityMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='senderDeviceId', full_name='measurements.DensityMap.senderDeviceId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='measurements.DensityMap.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=309,
)


_WARNMESSAGE = _descriptor.Descriptor(
  name='WarnMessage',
  full_name='measurements.WarnMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='measurements.WarnMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='validUntil', full_name='measurements.WarnMessage.validUntil', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='measurements.WarnMessage.latitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='measurements.WarnMessage.longitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=398,
)


_LOCATIONMESSAGEWRAPPER = _descriptor.Descriptor(
  name='LocationMessageWrapper',
  full_name='measurements.LocationMessageWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='single', full_name='measurements.LocationMessageWrapper.single', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='map', full_name='measurements.LocationMessageWrapper.map', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='measurements.LocationMessageWrapper.message', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='measurements.LocationMessageWrapper.msg',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=401,
  serialized_end=571,
)

_DENSITYMAP.fields_by_name['data'].message_type = _SINGLELOCATIONDATA
_LOCATIONMESSAGEWRAPPER.fields_by_name['single'].message_type = _SINGLELOCATIONDATA
_LOCATIONMESSAGEWRAPPER.fields_by_name['map'].message_type = _DENSITYMAP
_LOCATIONMESSAGEWRAPPER.fields_by_name['message'].message_type = _WARNMESSAGE
_LOCATIONMESSAGEWRAPPER.oneofs_by_name['msg'].fields.append(
  _LOCATIONMESSAGEWRAPPER.fields_by_name['single'])
_LOCATIONMESSAGEWRAPPER.fields_by_name['single'].containing_oneof = _LOCATIONMESSAGEWRAPPER.oneofs_by_name['msg']
_LOCATIONMESSAGEWRAPPER.oneofs_by_name['msg'].fields.append(
  _LOCATIONMESSAGEWRAPPER.fields_by_name['map'])
_LOCATIONMESSAGEWRAPPER.fields_by_name['map'].containing_oneof = _LOCATIONMESSAGEWRAPPER.oneofs_by_name['msg']
_LOCATIONMESSAGEWRAPPER.oneofs_by_name['msg'].fields.append(
  _LOCATIONMESSAGEWRAPPER.fields_by_name['message'])
_LOCATIONMESSAGEWRAPPER.fields_by_name['message'].containing_oneof = _LOCATIONMESSAGEWRAPPER.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['SingleLocationData'] = _SINGLELOCATIONDATA
DESCRIPTOR.message_types_by_name['DensityMap'] = _DENSITYMAP
DESCRIPTOR.message_types_by_name['WarnMessage'] = _WARNMESSAGE
DESCRIPTOR.message_types_by_name['LocationMessageWrapper'] = _LOCATIONMESSAGEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SingleLocationData = _reflection.GeneratedProtocolMessageType('SingleLocationData', (_message.Message,), {
  'DESCRIPTOR' : _SINGLELOCATIONDATA,
  '__module__' : 'payload_pb2'
  # @@protoc_insertion_point(class_scope:measurements.SingleLocationData)
  })
_sym_db.RegisterMessage(SingleLocationData)

DensityMap = _reflection.GeneratedProtocolMessageType('DensityMap', (_message.Message,), {
  'DESCRIPTOR' : _DENSITYMAP,
  '__module__' : 'payload_pb2'
  # @@protoc_insertion_point(class_scope:measurements.DensityMap)
  })
_sym_db.RegisterMessage(DensityMap)

WarnMessage = _reflection.GeneratedProtocolMessageType('WarnMessage', (_message.Message,), {
  'DESCRIPTOR' : _WARNMESSAGE,
  '__module__' : 'payload_pb2'
  # @@protoc_insertion_point(class_scope:measurements.WarnMessage)
  })
_sym_db.RegisterMessage(WarnMessage)

LocationMessageWrapper = _reflection.GeneratedProtocolMessageType('LocationMessageWrapper', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONMESSAGEWRAPPER,
  '__module__' : 'payload_pb2'
  # @@protoc_insertion_point(class_scope:measurements.LocationMessageWrapper)
  })
_sym_db.RegisterMessage(LocationMessageWrapper)


# @@protoc_insertion_point(module_scope)
